// Sway: preset registry (ids, params) and localized name/description lookup
const PRESETS = {
  none:      ['Không hiệu ứng', {}, 'Giữ nguyên âm thanh, chỉ chuyển sang định dạng đã chọn'],
  flmobile:  ['FL Mobile gốc', { pmode: 'lr', bars: 4, panAmt: 50, rv: 'hall', revAmt: 100, mix: 25 }, 'Panner trái↔phải + reverb, đúng mẫu FL Mobile'],
  c8d:       ['8D vòng tròn', { pmode: 'circle', bars: 4, panAmt: 100, rv: 'room', revAmt: 50, mix: 15 }, 'Âm thanh xoay quanh đầu (nên dùng tai nghe)'],
  xuanha:    ['Xuân-Hạ', {}, 'Hai file tách hai bên: file 1 bên trái, file 2 bên phải (cần chọn đúng 2 file)'],
  slowed:    ['Slowed + reverb', { speed: 80, rv: 'big', revAmt: 30, mix: 40, eq: 'warm', pmode: 'off' }, 'Chậm lại, trầm hơn, reverb dày'],
  nightcore: ['Nightcore', { speed: 125, rv: 'room_s', revAmt: 0, mix: 10, eq: 'bright', pmode: 'off' }, 'Nhanh hơn, cao và sáng hơn'],
  bighall:   ['Hall lớn mơ màng', { pmode: 'off', rv: 'big', revAmt: 40, mix: 45, decay: 120 }, 'Không gian rộng như nhà hát, không có panner'],
  c8d_slow:  ['8D chậm mơ màng', { pmode: 'circle', bars: 8, panAmt: 100, rv: 'big', revAmt: 60, mix: 30, eq: 'warm' }, 'Xoay chậm, reverb lớn, âm ấm'],
  c8d_fast:  ['8D nhanh', { pmode: 'circle', bars: 2, panAmt: 100, rv: 'room_s', revAmt: 50, mix: 12 }, 'Xoay nhanh, sôi động'],
  c8d_rev:   ['8D ngược chiều', { pmode: 'circle_rev', bars: 4, panAmt: 100, rv: 'hall', revAmt: 50, mix: 20 }, 'Xoay ngược chiều kim đồng hồ'],
  swing:     ['Lắc phía trước mặt', { pmode: 'swing_front', bars: 2, panAmt: 100, rv: 'room', revAmt: 50, mix: 15 }, 'Lắc qua lại phía trước'],
  fig8:      ['Hình số 8 quanh đầu', { pmode: 'fig8', bars: 4, panAmt: 100, rv: 'hall', revAmt: 50, mix: 20 }, 'Bay hình số 8 quanh đầu'],
  drift:     ['Trôi ngẫu nhiên thư giãn', { pmode: 'drift', bars: 8, panAmt: 100, rv: 'big', revAmt: 60, mix: 30, eq: 'warm' }, 'Trôi nhẹ nhàng khắp không gian'],
  space:     ['Echo vũ trụ', { pmode: 'drift', bars: 8, panAmt: 100, rv: 'big', revAmt: 50, mix: 35, dly: 'd8', fb: 60, dmix: 40 }, 'Echo lơ lửng giữa không gian'],
  pingpong:  ['Ping-pong stereo + echo', { pmode: 'lr', pshape: 'tri', bars: 1, panAmt: 100, rv: 'room', revAmt: 30, mix: 10, dly: 'e8', fb: 45, dmix: 25 }, 'Nhảy trái-phải kèm echo'],
  cave:      ['Hang động', { pmode: 'off', rv: 'big', revAmt: 40, mix: 50, decay: 160, eq: 'muffled', dly: 'q', fb: 50, dmix: 25 }, 'Vang sâu, tối và có tiếng vọng'],
  stadium:   ['Sân vận động', { pmode: 'off', rv: 'big', revAmt: 30, mix: 35, dly: 'h', fb: 35, dmix: 25 }, 'Vang lớn kèm tiếng vọng xa'],
  dream:     ['Mơ màng (8D + chorus)', { pmode: 'circle', bars: 8, panAmt: 70, rv: 'big', revAmt: 60, mix: 35, fxm: 'chorus' }, 'Xoay nhẹ, dày và lung linh'],
  podcast:   ['Podcast / giọng nói', { pmode: 'off', dn: '20', comp: 'mid', eq: 'warm', trebdb: 2, lufs: '-16' }, 'Khử nhiễu, nén động, chuẩn -16 LUFS'],
  karaoke:   ['Karaoke (giảm giọng)', { pmode: 'off', kara: 90 }, 'Giảm phần chính giữa, nơi thường là giọng hát'],
  vocal:     ['Làm nổi bật giọng', { pmode: 'off', middb: 4, trebdb: 2, comp: 'soft' }, 'Tăng dải giọng, nén nhẹ'],
  telephone: ['Điện thoại', { pmode: 'off', eq: 'radio', comp: 'hard', width: 0 }, 'Tiếng hẹp, mono như qua điện thoại'],
  megaphone: ['Loa phóng thanh', { pmode: 'off', eq: 'radio', comp: 'hard', rv: 'room_s', revAmt: 0, mix: 15 }, 'Gắt, hẹp, hơi vang'],
  deep:      ['Giọng trầm', { pmode: 'off', semis: -4 }, 'Hạ cao độ 4 bán cung, giữ nguyên tốc độ'],
  chip:      ['Giọng cao (chipmunk)', { pmode: 'off', semis: 7 }, 'Nâng cao độ 7 bán cung, giữ nguyên tốc độ'],
  vapor:     ['Vaporwave', { pmode: 'off', speed: 80, fxm: 'chorus', rv: 'big', revAmt: 30, mix: 40, eq: 'warm' }, 'Chậm, trầm, chorus và reverb lớn'],
  fast2:     ['Nhanh gấp đôi (giữ cao độ)', { pmode: 'off', speed: 200, spdm: 'keep' }, 'Tăng tốc 2×, cao độ không đổi'],
  slow2:     ['Chậm một nửa (giữ cao độ)', { pmode: 'off', speed: 50, spdm: 'keep' }, 'Giảm tốc 0,5×, cao độ không đổi'],
  down2:     ['Hạ 2 bán cung', { pmode: 'off', semis: -2 }, 'Hạ giọng một cung, giữ tốc độ'],
  up2:       ['Nâng 2 bán cung', { pmode: 'off', semis: 2 }, 'Nâng giọng một cung, giữ tốc độ'],
  lofi:      ['Lo-fi chill', { pmode: 'off', fxm: 'lofi', eq: 'warm', rv: 'room_s', revAmt: 0, mix: 15, comp: 'soft' }, 'Ấm, hơi rè, thư giãn'],
  radio:     ['Radio cũ', { pmode: 'off', rv: 'room_s', revAmt: 0, mix: 10, eq: 'radio', width: 30 }, 'Giọng radio cũ, hẹp'],
  muffled:   ['Nghe qua tường (nghẹt)', { pmode: 'off', rv: 'room', revAmt: 0, mix: 15, eq: 'muffled', width: 60 }, 'Như nghe từ phòng bên cạnh'],
  under:     ['Dưới nước', { pmode: 'off', eq: 'muffled', fxm: 'chorus', rv: 'big', revAmt: 30, mix: 30 }, 'Tối, lắc lư và vang'],
  tape:      ['Băng cassette cũ', { pmode: 'off', fxm: 'vibrato', eq: 'warm', width: 70, rv: 'room_s', revAmt: 0, mix: 10 }, 'Rung nhẹ, ấm và hẹp'],
  stream14:  ['Chuẩn Spotify / YouTube', { pmode: 'off', comp: 'soft', lufs: '-14' }, 'Nén nhẹ, chuẩn -14 LUFS'],
  loud:      ['Nghe to và đầy', { pmode: 'off', comp: 'mid', bassdb: 3, trebdb: 2, lufs: '-14' }, 'Nén vừa, thêm bass và treble'],
  bassw:     ['Bass mạnh + stereo rộng', { pmode: 'off', rv: 'off', eq: 'bass', width: 150 }, 'Bass dày, stereo rộng'],
  wide:      ['Stereo rộng', { pmode: 'off', width: 170 }, 'Mở rộng không gian trái-phải'],
  denoise:   ['Khử nhiễu', { pmode: 'off', dn: '20' }, 'Giảm tiếng ù, rè nền'],
  reverse:   ['Phát ngược', { pmode: 'off', rev: 'on' }, 'Đảo ngược toàn bộ âm thanh'],
  fade:      ['Fade in 3 giây, fade out 5 giây', { pmode: 'off', fin: 3, fout: 5 }, 'Vào và ra êm ái'],
};
const PGROUPS = [
  ['Phổ biến', ['none', 'flmobile', 'c8d', 'slowed', 'nightcore', 'bighall', 'xuanha']],
  ['8D và không gian', ['c8d_slow', 'c8d_fast', 'c8d_rev', 'swing', 'fig8', 'drift', 'dream', 'space', 'pingpong', 'cave', 'stadium']],
  ['Giọng và nhạc cụ', ['podcast', 'karaoke', 'vocal', 'telephone', 'megaphone', 'deep', 'chip']],
  ['Tốc độ và cao độ', ['vapor', 'fast2', 'slow2', 'down2', 'up2']],
  ['Lo-fi và retro', ['lofi', 'radio', 'muffled', 'under', 'tape']],
  ['Master và tiện ích', ['stream14', 'loud', 'bassw', 'wide', 'denoise', 'reverse', 'fade']],
];
const DESC = Object.fromEntries(Object.entries(PRESETS).map(([k, v]) => [k, v[2]]));
const PL = { zh: 0, en: 2 };
const pname = k => (LANG !== 'vi' && PT[k]) ? PT[k][PL[LANG]] : (D['p.' + k] ? t('p.' + k) : PRESETS[k][0]);
const pdesc = k => (LANG !== 'vi' && PT[k]) ? PT[k][PL[LANG] + 1] : (D['d.' + k] ? t('d.' + k) : (DESC[k] || t('d.custom')));
